const { Router } = require("express");

const router = Router();

router.get("/", async (req, res) => {
  res.send([
    {
      sections: [
        {
          id: 178,
          days: "Mon,Wed,Fri",
          room: "",
          start: "13:25:00",
          end: "14:15:00",
          type: "Lecture",
          title: "CASAS100 A1",
          professor: "Michael Mendillo",
        },
        {
          id: 179,
          days: "Mon",
          room: "",
          start: "14:30:00",
          end: "15:20:00",
          type: "Discussion",
          title: "CASAS100 A2",
          professor: "Michael Mendillo",
        },
        {
          id: 1564,
          days: "Tue,Thu",
          room: "",
          start: "11:00:00",
          end: "12:15:00",
          type: "Lecture",
          title: "CASCS112 A1",
          professor: "Christine Papadakis-Kanaris",
        },
        {
          id: 1567,
          days: "Fri",
          room: "",
          start: "09:05:00",
          end: "09:55:00",
          type: "Lab",
          title: "CASCS112 A3",
          professor: "Christine Papadakis-Kanaris",
        },
        {
          id: 1592,
          days: "Tue,Thu",
          room: "",
          start: "14:00:00",
          end: "15:15:00",
          type: "Lecture",
          title: "CASCS132 A1",
          professor: "Abbas Attarwala",
        },
        {
          id: 1594,
          days: "Mon",
          room: "",
          start: "09:05:00",
          end: "09:55:00",
          type: "Discussion",
          title: "CASCS132 A3",
          professor: "Abbas Attarwala",
        },
        {
          id: 2275,
          days: "Mon,Wed,Fri",
          room: "",
          start: "10:10:00",
          end: "11:00:00",
          type: "Independent",
          title: "CASJS100 A1",
          professor: "Ingrid Anderson",
        },
      ],
      title: "Nexus Recommended",
    },
    {
      sections: [
        {
          id: 178,
          days: "Mon,Wed,Fri",
          room: "",
          start: "13:25:00",
          end: "14:15:00",
          type: "Lecture",
          title: "CASAS100 A1",
          professor: "Michael Mendillo",
        },
        {
          id: 179,
          days: "Mon",
          room: "",
          start: "14:30:00",
          end: "15:20:00",
          type: "Discussion",
          title: "CASAS100 A2",
          professor: "Michael Mendillo",
        },
        {
          id: 1564,
          days: "Tue,Thu",
          room: "",
          start: "11:00:00",
          end: "12:15:00",
          type: "Lecture",
          title: "CASCS112 A1",
          professor: "Christine Papadakis-Kanaris",
        },
        {
          id: 1567,
          days: "Fri",
          room: "",
          start: "09:05:00",
          end: "09:55:00",
          type: "Lab",
          title: "CASCS112 A3",
          professor: "Christine Papadakis-Kanaris",
        },
        {
          id: 1592,
          days: "Tue,Thu",
          room: "",
          start: "14:00:00",
          end: "15:15:00",
          type: "Lecture",
          title: "CASCS132 A1",
          professor: "Abbas Attarwala",
        },
        {
          id: 1594,
          days: "Mon",
          room: "",
          start: "09:05:00",
          end: "09:55:00",
          type: "Discussion",
          title: "CASCS132 A3",
          professor: "Abbas Attarwala",
        },
      ],
      title: "Prioritize Major",
    },
  ]);
});

module.exports = router;
